# Generated by Django 4.2.14 on 2024-08-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agriculturalparcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("farm_name", models.CharField(max_length=255)),
                ("plot_name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "agriculturalparcel",
                "managed": False,
            },
        ),
    ]
